"""request

Revision ID: 1ec1900afe26
Revises: 61310209ba30
Create Date: 2025-05-13 16:30:34.656978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec1900afe26'
down_revision = '61310209ba30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'report_cycle', ['cycle_id'], ['cycle_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cycle_id')

    # ### end Alembic commands ###
